version: "3"
services:
  app:
    image: us.gcr.io/acm-inter-staging/acm.dp.eq.helper.phpmyadmin:4.8.5
    build:
      context: ..
      

    ports:
      - 443:443
      - 80:80
    command: httpd -DFOREGROUND
