################################################################################
################################################################################

kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "etl-eq-build" 
spec:
  nodeSelector:
    deployment-nodegroup: "<%- ENV_TIER %>"
  source:
    type: "Git"
    git: 
      uri: "<%- BITBUCKET_DSL_REPO %>"
      <% if (TAG_NAME == 'latest') { %>
      ref: "master"
      <% } else { %>
      ref: "<%- TAG_NAME %>"
      <% } %>
    sourceSecret:
      name: "git-token"
    dockerfile: >-
      FROM <%- GCR_BASE %>/acn.dp.generic.database.etl.base:latest

      # Use ETL root path, as buildconfig in OCP will consider the project at the root level instead of relative path.
      
      ADD ETL/config /usr/src/app/target/profile

      RUN ls -al /usr/src/app/target/profile
      
      <% if (ETL_APPLICATION == 'equator') { %>
      USER root

      RUN ln -s /usr/src/app/target/profile/acm-eq /usr/src/app/target/profile/acm-eq-vault
      
      USER etl
      <% } %>

  strategy: 
    type: "Docker"
    dockerStrategy:
      contextDir: "ETL"
      forcePull: true
      pullSecret:
        name: "gcr-docker-oauth"
  resources: 
    limits: 
      cpu: "512m"
      memory: "512Mi"
    requests:
      cpu: "128m"
      memory: "256Mi"
  output:
    to:
      kind: "DockerImage"
      name: "<%- GCR_BASE %>/<%- ETL_IMAGE_PROJECT %>:<%- TAG_NAME -%>"
    pushSecret:
      name: "gcr-docker-oauth"

################################################################################
################################################################################
