apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: phpmyadmin
      name: phpmyadmin
    spec:
      replicas: 1
      selector:
        name: phpmyadmin
      template:
        metadata:
          creationTimestamp: null
          labels:
            name: phpmyadmin
        spec:
          imagePullSecrets:
          - name: gcr-docker-oauth
          containers:
            - image: us.gcr.io/acm-inter-staging/acm.dp.eq.helper.phpmyadmin:4.8.5
              name: phpmyadmin
              command:
                - sleep
              args:
                - infinity
              imagePullPolicy: Always
              env:
                - name: PMA_HOST
                  value: "10.14.24.200"
                - name: PMA_PORT
                  value: "3306"
          
