serviceAccountJson: gcp-gcs.json
secretName: gcp-dp-gcs

_job: &default_job
  envTier: staging
  fetchFromLastSuccess: "1 hour ago"
  username: "{crypt}AM6XgWxlQ75wgyyM_4XfFOhelP64jAdm4sZlLeYFlvU4ZpgW9p3yRNF6xS24_n8GQCoFPWX9DB4f"
  password: "{crypt}AM6XgWw-qwqAsUyKtUHfzxrjNW3ZGj-BgBk4x07Yo7AbVkAfAylEvLDg23du-gem-PyfzwBfrn_KjirqQsd9jSQuv2A8EmDDKAowytE0IFA17Ks4SQBlaBw"
  bucketName: acm-dp-ocp-eq-vn-staging-source-archive
  trigger_cron: "H */1 * * *"

jobs:
  - ETL:
    - eq.agent.accreditation:
        <<: *default_job
        profile: acm-eq/agent_accreditation
        dataSourceUrl: jdbc:mysql://10.14.24.200:3306/agent_dev
        
    - eq.agent.additional:
        <<: *default_job
        profile: acm-eq/agent_additional
        dataSourceUrl: jdbc:mysql://10.14.24.200:3306/agent_dev?useUnicode=yes&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=UTC
