serviceAccountJson: gcp-gcs.json
secretName: gcp-dp-gcs

_job: &default_job
  envTier: staging
  fetchFromLastSuccess: "1 hour ago"
  username: "{crypt}ADAfIeF-buwkHykM20_Kx81Ro9rBsBIfCO6vOZq7Wja3KwLOgFHTP4on4Dv8VS8oCKT3RFmP1N3v"
  password: "{crypt}ADAfIeHUGfzCgrfWy4_HYwfMvrYIRixBnUtpcV0WEuskFaAJbzUyZ_VjThjbsYY1actMJwHWWL8RFAI3XzuJIor6OHcXrRF0oKkLYBUmVQYQ7iQCUuSv8z8"
  bucketName: acm-dp-ocp-eq-vn-staging-source-archive
  trigger_cron: "H */1 * * *"

jobs:
  - ETL:
    - eq.agent.accreditation:
        <<: *default_job
        profile: acm-eq/agent_accreditation
        dataSourceUrl: jdbc:mysql://10.14.24.200:3306/agent_dev
        
    - eq.agent.additional:
        <<: *default_job
        profile: acm-eq/agent_additional
        dataSourceUrl: jdbc:mysql://10.14.24.200:3306/agent_dev?useUnicode=yes&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=UTC
